### PR TITLE
Add RenameInternalized support

### PR DESCRIPTION
**Pull request by luludotdev**

### CODE REVIEW

**Comment by peters** [comment]
Thanks! :)

**Comment by levdimov** [comment]
Hello! 
Could you please publish this fix to NuGet? 
Thanks!

**Comment by luludotdev** [comment]
@levdimov I published my fork of this package to NuGet to use while this PR was pending, you can view it [here](https://www.nuget.org/packages/ILRepack.MSBuild.Task.RenameInternal/).

**Comment by replaysMike** [comment]
yea I'm surprised they didn't push this by now, I really need this feature. Switching to @lolPants fork

EDIT: Nope, @lolPants props file error:
```
The imported project "C:\Users\mikeb\.nuget\packages\ilrepack.msbuild.task.renameinternal\2.0.16\build\ILRepack.MSBuild.Task.props" was not found. Confirm that the expression in the Import declaration "..\build\ILRepack.MSBuild.Task.props" is correct, and that the file exists on disk.	AnySerializer	C:\Users\mikeb\.nuget\packages\ilrepack.msbuild.task.renameinternal\2.0.16\buildMultiTargeting\ILRepack.MSBuild.Task.RenameInternal.props	6	
```

**Pull request merged**
