### PR TITLE
Migration Guide

### PR DESCRIPTION
**Pull request by fberasategui**
Added a document detailing steps required to migrate from V1 to V2 of this package.

### CODE REVIEW

**Comment by peters** [comment]
@fberasategui Thanks for taking the time to write a migration guide. Great work :) Could you update the part about the `KeyFile` property not being available in `v2` ? It should be fixed in the latest release.

**Comment by peters** [comment]
@fberasategui ping

**Comment by fberasategui** [comment]
@peters sorry for that. I've been pretty busy these days.

I still got several problems with V2, so I decided to downgrade to V1. Not sure if you can help with that. I'll raise a separate issue about it.

**Comment by fberasategui** [comment]
@peters updated PR

**Comment by peters** [comment]
@fberasategui Thank you! :)

**Pull request merged**
